import { createHash } from "node:crypto";

import type {
  ComputerSubagentProviderLaunchInput,
  ComputerSubagentProviderOutcome,
  ComputerSubagentProviderRuntime,
} from "./computer-subagent-runtime.ts";
import type { ProviderAdapter, RuntimeEvent, SendTurnInput } from "./contracts.ts";
import { BoundedReplyAccumulator } from "./reply-accumulator.ts";

export const COMPUTER_OPERATOR_OUTPUT_MAX_BYTES = 32_000;

export interface ComputerOperatorProviderPreparation {
  adapter: ProviderAdapter;
  /** Harness-prepared child input. Exact identity, task, and model are always
   * overwritten by this wrapper and cannot be selected by the provider. */
  turn?: Omit<SendTurnInput, "threadId" | "turnId" | "text" | "model" | "resumeCursor" | "transcript">;
}

export interface ComputerOperatorProviderOptions {
  prepare: (input: ComputerSubagentProviderLaunchInput) => Promise<ComputerOperatorProviderPreparation>;
}

interface Deferred<T> {
  promise: Promise<T>;
  resolve: (value: T) => void;
}

function deferred<T>(): Deferred<T> {
  let resolve!: (value: T) => void;
  const promise = new Promise<T>((done) => { resolve = done; });
  return { promise, resolve };
}

/** Child ids are generated by the trusted manager, but hashing also keeps a
 * deterministic test-supplied id out of provider filesystem/session names. */
export function computerOperatorChildThreadId(childId: string): string {
  return `computer-operator-${createHash("sha256").update(childId).digest("hex").slice(0, 32)}`;
}

function completedNormally(event: Extract<RuntimeEvent, { type: "turn.completed" }>): boolean {
  return event.ok && !/(?:cancel|interrupt|timeout|stopp)/i.test(event.stopReason ?? "");
}

/** Generic adapter-backed hidden child. It deliberately bypasses the main
 * conversation fold: index supplies the selected adapter and exact scoped
 * integrations, while this wrapper owns only child event correlation. */
export function createComputerOperatorProviderRuntime(
  options: ComputerOperatorProviderOptions,
): ComputerSubagentProviderRuntime {
  return {
    launch: async (input) => {
      const prepared = await options.prepare(input);
      const { adapter } = prepared;
      const threadId = computerOperatorChildThreadId(input.childId);
      const turnId = input.childId;
      const output = new BoundedReplyAccumulator(COMPUTER_OPERATOR_OUTPUT_MAX_BYTES);
      const terminal = deferred<void>();
      const completion = deferred<ComputerSubagentProviderOutcome>();
      let settled = false;
      let unsubscribe: (() => void) | null = null;

      const settle = (outcome: ComputerSubagentProviderOutcome) => {
        if (settled) return;
        settled = true;
        unsubscribe?.();
        unsubscribe = null;
        completion.resolve(outcome);
        terminal.resolve();
      };

      // Subscribe before sendTurn: a fast fake/API adapter may settle before
      // registration returns, and losing that event would retain the lease.
      unsubscribe = adapter.onEvent((event) => {
        if (event.threadId !== threadId || event.turnId !== turnId) return;
        if (event.type === "item.completed" && event.itemType === "assistant_text") {
          output.append(event.text);
          return;
        }
        if (event.type === "turn.completed") {
          if (completedNormally(event)) settle({ status: "completed", ...(output.text ? { output: output.text } : {}) });
          else if (/(?:cancel|interrupt|stopp)/i.test(event.stopReason ?? "")) {
            settle({ status: "aborted", reason: event.stopReason ?? "computer operator was interrupted" });
          } else {
            settle({ status: "failed", error: event.stopReason ?? "computer operator failed" });
          }
          return;
        }
        if (event.type === "session.exited") {
          settle({ status: "failed", error: "computer operator provider session exited before terminal completion" });
        }
      });

      try {
        const started = await adapter.sendTurn({
          ...(prepared.turn ?? {}),
          threadId,
          turnId,
          isolationKey: prepared.turn?.isolationKey ?? threadId,
          text: input.prompt,
          model: input.model.model,
          // Hidden operator children are deliberately fresh and receive no
          // parent transcript or provider-native continuation.
          resumeCursor: undefined,
          transcript: undefined,
        });
        if (started.turnId !== turnId) {
          await adapter.interruptTurn(threadId, started.turnId).catch(() => undefined);
          throw new Error("computer operator provider returned a mismatched turn id");
        }
      } catch (error) {
        unsubscribe?.();
        unsubscribe = null;
        throw error;
      }

      let interruptPromise: Promise<void> | null = null;
      return {
        completion: completion.promise,
        waitForTerminal: () => terminal.promise,
        interrupt: () => {
          interruptPromise ??= adapter.interruptTurn(threadId, turnId);
          return interruptPromise;
        },
      };
    },
  };
}
