/** Positive environment construction for provider CLIs.
 *
 * The harness process can hold unrelated API keys, UI bearers, SSH agents,
 * deployment controls, and user app credentials. A denylist inevitably
 * misses the next variable somebody adds, so provider children start from a
 * small non-secret OS base and receive only:
 *   - environment explicitly configured for this provider instance;
 *   - credential names explicitly declared by that driver; and
 *   - exact turn-scoped values generated by trusted harness code.
 */

const SAFE_AMBIENT_NAMES = [
  "HOME",
  "USERPROFILE",
  "USER",
  "LOGNAME",
  "SHELL",
  "TMPDIR",
  "TMP",
  "TEMP",
  "LANG",
  "LANGUAGE",
  "LC_ALL",
  "LC_CTYPE",
  "TERM",
  "COLORTERM",
  "NO_COLOR",
  "FORCE_COLOR",
  "TZ",
  "XDG_CONFIG_HOME",
  "XDG_CACHE_HOME",
  "XDG_DATA_HOME",
  "XDG_STATE_HOME",
  "SYSTEMROOT",
  "WINDIR",
  "COMSPEC",
  "PATHEXT",
  "APPDATA",
  "LOCALAPPDATA",
  "PROGRAMDATA",
  "SSL_CERT_FILE",
  "SSL_CERT_DIR",
  "NODE_EXTRA_CA_CERTS",
] as const;

const RESERVED_EXPLICIT_NAMES = new Set([
  "OMB_UI_SESSION_TOKEN",
  "OMB_UI_SESSION_TOKEN_SHA256",
  "OMB_COMPANION_SESSION_TOKEN",
  "OMB_PROVIDER_LAUNCHER",
  "OMB_PROVIDER_LAUNCH_MANIFEST",
  "OMB_PROVIDER_SANDBOX_PATHS",
  "OMB_PROVIDER_TURN_DIR",
  "OMB_REQUIRE_PROVIDER_ISOLATION",
  "OMB_MODEL_RELAY_OPENAI_BASE_URL",
  "OMB_MODEL_RELAY_ANTHROPIC_BASE_URL",
  "OMB_MODEL_RELAY_TOKEN",
  "OMB_MODEL_RELAY_HOST",
  "OMB_MODEL_RELAY_MODEL",
  // Trusted-server local-host discovery/source settings. A child gets only the
  // generated relay connection, never an upstream URL or host credential.
  "OPENMAUSBOT_DESKTOP2_QWEN_URL",
  "OPENMAUSBOT_SPARK_GLM_URL",
  "UNSLOTH_STUDIO_AUTH_TOKEN",
]);

export function providerChildEnvironment(
  explicit: Record<string, string | undefined> = {},
  options: {
    credentialEnv?: readonly string[];
    internal?: Record<string, string | undefined>;
    ambient?: NodeJS.ProcessEnv;
  } = {},
): NodeJS.ProcessEnv {
  const ambient = options.ambient ?? process.env;
  const next: NodeJS.ProcessEnv = {};
  for (const name of SAFE_AMBIENT_NAMES) {
    if (ambient[name] !== undefined) next[name] = ambient[name];
  }
  // Test fixture controls are intentionally available only inside Vitest;
  // production never has a prefix-based ambient escape hatch.
  if (ambient.VITEST) {
    next.VITEST = ambient.VITEST;
    for (const [name, value] of Object.entries(ambient)) {
      if (name.startsWith("FAKE_") && value !== undefined) next[name] = value;
    }
  }
  for (const name of options.credentialEnv ?? []) {
    const value = explicit[name] ?? ambient[name];
    if (value !== undefined) next[name] = value;
  }
  for (const [name, value] of Object.entries(explicit)) {
    if (RESERVED_EXPLICIT_NAMES.has(name)) continue;
    if (value !== undefined) next[name] = value;
  }
  for (const [name, value] of Object.entries(options.internal ?? {})) {
    if (value !== undefined) next[name] = value;
    else delete next[name];
  }
  return next;
}
